In [1]:
import os, sys
import general_config 
print(general_config.ROOTDIR)
sys.path.append(general_config.ROOTDIR)

In [2]:
import numpy as np

In [3]:
x = np.linspace(-1,1,21).reshape(3,7)
print(x)
print(np.clip(x,0,1))

[[-1.  -0.9 -0.8 -0.7 -0.6 -0.5 -0.4]
 [-0.3 -0.2 -0.1  0.   0.1  0.2  0.3]
 [ 0.4  0.5  0.6  0.7  0.8  0.9  1. ]]
[[0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.1 0.2 0.3]
 [0.4 0.5 0.6 0.7 0.8 0.9 1. ]]


In [4]:
from pipeline.eval.eval_metrics import FiveBandXAIMetric
xai = FiveBandXAIMetric()
C,H,W = 3,2,5

In [5]:
setting = {
    'xai_channel_transformation': 'clamp_then_sum_pixels_over_channels',
    'sum_pixels_over_channels': {
        'normalize': 'absmax_after_sum'
    },
    'clamp_setting':{
        'min_max': [-0.5,0.5],
    },
    'five_band_stratification':{
        'thresholds': np.array([-0.9, -0.5, 0.5, 0.9]),
        'targets': np.array([-2,-1,0,1,2]),                     
    },
    'soft_delta':0.05,
    'n_soft_steps':7,
}

In [6]:
h0 = np.linspace(-1,1,H*W,)
h0 = np.round(h0,3)
h0 = np.array(h0).reshape(H,W)
h = np.stack((h0,h0,h0))
print('h0\n',h0)
print('h0.shape:',h0.shape)
print('h\n',h)
print('h.shape',h.shape)
metrics = xai.fiveband_score(h, h0, verbose=250, setting=setting)
print(metrics)

h0
 [[-1.    -0.778 -0.556 -0.333 -0.111]
 [ 0.111  0.333  0.556  0.778  1.   ]]
h0.shape: (2, 5)
h
 [[[-1.    -0.778 -0.556 -0.333 -0.111]
  [ 0.111  0.333  0.556  0.778  1.   ]]

 [[-1.    -0.778 -0.556 -0.333 -0.111]
  [ 0.111  0.333  0.556  0.778  1.   ]]

 [[-1.    -0.778 -0.556 -0.333 -0.111]
  [ 0.111  0.333  0.556  0.778  1.   ]]]
h.shape (3, 2, 5)
fiveband_score()
h after normalization
 [[-1.    -1.    -1.    -0.666 -0.222]
 [ 0.222  0.666  1.     1.     1.   ]]

After strat
 h.shape: (2, 5)
[[-2. -2. -2. -1.  0.]
 [ 0.  1.  2.  2.  2.]]
h0.shape: (2, 5)
[[-2. -1. -1.  0.  0.]
 [ 0.  0.  1.  1.  2.]]

binary_equality
 [[1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]]
TP
 [[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]
FP
 [[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]]
FN
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
{'pixel_acc': 0.4, 'recall': 0.99999950000025, 'precision': 0.49999987500003124}
