In [1]:
import os, sys
import general_config 
print(general_config.ROOTDIR)
sys.path.append(general_config.ROOTDIR)

D:/Desktop@D/xai_basic


In [2]:
import numpy as np

In [3]:
from pipeline.eval.eval_metrics import FiveBandXAIMetric
xai = FiveBandXAIMetric()
C,H,W = 3,2,5

In [4]:
h0 = np.linspace(-1,1,H*W,)
h0 = np.round(h0,3)
h0 = np.array(h0).reshape(H,W)
h0fs = xai.five_band_stratification(h0, setting=None)
print('after strat:',h0fs)
h = np.stack((h0,h0,h0))
print('h0\n',h0)
print('h0.shape:',h0.shape)
print('h\n',h)
print('h.shape',h.shape)
metrics = xai.fiveband_score(h, h0, verbose=250)
print(metrics)

after strat: [[-2. -2. -1. -1.  0.]
 [ 0.  1.  1.  2.  2.]]
h0
 [[-1.    -0.778 -0.556 -0.333 -0.111]
 [ 0.111  0.333  0.556  0.778  1.   ]]
h0.shape: (2, 5)
h
 [[[-1.    -0.778 -0.556 -0.333 -0.111]
  [ 0.111  0.333  0.556  0.778  1.   ]]

 [[-1.    -0.778 -0.556 -0.333 -0.111]
  [ 0.111  0.333  0.556  0.778  1.   ]]

 [[-1.    -0.778 -0.556 -0.333 -0.111]
  [ 0.111  0.333  0.556  0.778  1.   ]]]
h.shape (3, 2, 5)
fiveband_score()
h after normalization
 [[-1.    -0.778 -0.556 -0.333 -0.111]
 [ 0.111  0.333  0.556  0.778  1.   ]]

After strat
 h.shape: (2, 5)
[[-2. -2. -1. -1.  0.]
 [ 0.  1.  1.  2.  2.]]
h0.shape: (2, 5)
[[-2. -2. -1. -1.  0.]
 [ 0.  1.  1.  2.  2.]]

binary_equality
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
TP
 [[1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1.]]
FP
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
FN
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
{'pixel_acc': 1.0, 'recall': 0.9999998750000157, 'precision': 0.9999998750000157}


In [5]:
h0=np.linspace(-1,1,H*W,)
h0 = np.round(h0,3)
h0 = np.array(h0).reshape(H,W)
h = np.stack((h0,h0,h0))
h[0,0,:]=1
print('h0\n',h0)
print('h0.shape:',h0.shape)
print('h\n',h)
print('h.shape',h.shape)
metrics = xai.fiveband_score(h, h0, verbose=250)
print(metrics)

h0
 [[-1.    -0.778 -0.556 -0.333 -0.111]
 [ 0.111  0.333  0.556  0.778  1.   ]]
h0.shape: (2, 5)
h
 [[[ 1.     1.     1.     1.     1.   ]
  [ 0.111  0.333  0.556  0.778  1.   ]]

 [[-1.    -0.778 -0.556 -0.333 -0.111]
  [ 0.111  0.333  0.556  0.778  1.   ]]

 [[-1.    -0.778 -0.556 -0.333 -0.111]
  [ 0.111  0.333  0.556  0.778  1.   ]]]
h.shape (3, 2, 5)
fiveband_score()
h after normalization
 [[-0.33333333 -0.18533333 -0.03733333  0.11133333  0.25933333]
 [ 0.111       0.333       0.556       0.778       1.        ]]

After strat
 h.shape: (2, 5)
[[-1.  0.  0.  0.  0.]
 [ 0.  1.  1.  2.  2.]]
h0.shape: (2, 5)
[[-2. -2. -1. -1.  0.]
 [ 0.  1.  1.  2.  2.]]

binary_equality
 [[0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
TP
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1.]]
FP
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
FN
 [[0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
{'pixel_acc': 0.6, 'recall': 0.57142848979593, 'precision': 0.9999997500000625}


In [6]:
h0=np.linspace(-1,1,H*W,)
h0 = np.round(h0,3)
h0 = np.array(h0).reshape(H,W)
h = np.stack((h0,h0,h0))
h[0,0,:]=-1
print('h0\n',h0)
print('h0.shape:',h0.shape)
print('h\n',h)
print('h.shape',h.shape)
metrics = xai.fiveband_score(h, h0, verbose=250)
print(metrics)

h0
 [[-1.    -0.778 -0.556 -0.333 -0.111]
 [ 0.111  0.333  0.556  0.778  1.   ]]
h0.shape: (2, 5)
h
 [[[-1.    -1.    -1.    -1.    -1.   ]
  [ 0.111  0.333  0.556  0.778  1.   ]]

 [[-1.    -0.778 -0.556 -0.333 -0.111]
  [ 0.111  0.333  0.556  0.778  1.   ]]

 [[-1.    -0.778 -0.556 -0.333 -0.111]
  [ 0.111  0.333  0.556  0.778  1.   ]]]
h.shape (3, 2, 5)
fiveband_score()
h after normalization
 [[-1.         -0.852      -0.704      -0.55533333 -0.40733333]
 [ 0.111       0.333       0.556       0.778       1.        ]]

After strat
 h.shape: (2, 5)
[[-2. -2. -2. -1. -1.]
 [ 0.  1.  1.  2.  2.]]
h0.shape: (2, 5)
[[-2. -2. -1. -1.  0.]
 [ 0.  1.  1.  2.  2.]]

binary_equality
 [[1. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1.]]
TP
 [[1. 1. 0. 1. 0.]
 [0. 1. 1. 1. 1.]]
FP
 [[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]
FN
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
{'pixel_acc': 0.8, 'recall': 0.9999998571428775, 'precision': 0.8749998906250137}


In [7]:
h0=np.linspace(-1,1,H*W,)
h0 = np.round(h0,3)
h0 = np.array(h0).reshape(H,W)
h = np.stack((h0,h0,h0))
h0[0,:]=0
print('h0\n',h0)
print('h0.shape:',h0.shape)
print('h\n',h)
print('h.shape',h.shape)
metrics = xai.fiveband_score(h, h0, verbose=250)
print(metrics)

h0
 [[0.    0.    0.    0.    0.   ]
 [0.111 0.333 0.556 0.778 1.   ]]
h0.shape: (2, 5)
h
 [[[-1.    -0.778 -0.556 -0.333 -0.111]
  [ 0.111  0.333  0.556  0.778  1.   ]]

 [[-1.    -0.778 -0.556 -0.333 -0.111]
  [ 0.111  0.333  0.556  0.778  1.   ]]

 [[-1.    -0.778 -0.556 -0.333 -0.111]
  [ 0.111  0.333  0.556  0.778  1.   ]]]
h.shape (3, 2, 5)
fiveband_score()
h after normalization
 [[-1.    -0.778 -0.556 -0.333 -0.111]
 [ 0.111  0.333  0.556  0.778  1.   ]]

After strat
 h.shape: (2, 5)
[[-2. -2. -1. -1.  0.]
 [ 0.  1.  1.  2.  2.]]
h0.shape: (2, 5)
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 2. 2.]]

binary_equality
 [[0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
TP
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1.]]
FP
 [[1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
FN
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
{'pixel_acc': 0.6, 'recall': 0.9999997500000625, 'precision': 0.4999999375000079}


In [8]:
h0=np.linspace(-1,1,H*W,)
h0 = np.round(h0,3)
h0 = np.array(h0).reshape(H,W)
h = np.stack((h0,h0,h0))
h0[0,:]=0
h[:,1,:]=0
print('h0\n',h0)
print('h0.shape:',h0.shape)
print('h\n',h)
print('h.shape',h.shape)
metrics = xai.fiveband_score(h, h0, verbose=250)
print(metrics)

h0
 [[0.    0.    0.    0.    0.   ]
 [0.111 0.333 0.556 0.778 1.   ]]
h0.shape: (2, 5)
h
 [[[-1.    -0.778 -0.556 -0.333 -0.111]
  [ 0.     0.     0.     0.     0.   ]]

 [[-1.    -0.778 -0.556 -0.333 -0.111]
  [ 0.     0.     0.     0.     0.   ]]

 [[-1.    -0.778 -0.556 -0.333 -0.111]
  [ 0.     0.     0.     0.     0.   ]]]
h.shape (3, 2, 5)
fiveband_score()
h after normalization
 [[-1.    -0.778 -0.556 -0.333 -0.111]
 [ 0.     0.     0.     0.     0.   ]]

After strat
 h.shape: (2, 5)
[[-2. -2. -1. -1.  0.]
 [ 0.  0.  0.  0.  0.]]
h0.shape: (2, 5)
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 2. 2.]]

binary_equality
 [[0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
TP
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
FP
 [[1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
FN
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1.]]
{'pixel_acc': 0.2, 'recall': 0.0, 'precision': 0.0}
